import SelectColumnFilter from "./SelectColumnFilter";

export const columnData = [
  {
    Header: "ID",
    accessor: "id",
    disableFilters: true,
  },
  {
    Header: "Job Title",
    accessor: "title",
    Filter: SelectColumnFilter,
    filter: "includes",
  },
  {
    Header: "Location",
    accessor: "location",
    Filter: SelectColumnFilter,
    filter: "includes",
  },
  {
    Header: "Salary",
    accessor: "salary",
    Filter: SelectColumnFilter,
    filter: "includes",
  },
  {
    Header: "Company",
    accessor: "company",
    Filter: SelectColumnFilter,
    filter: "includes",
  },
  {
    Header: "Benefits",
    accessor: "benefits",
    disableFilters: true,
  },
  {
    Header: "Contact Name",
    accessor: "contactName",
    disableFilters: true,
  },
  {
    Header: "Contact Number",
    accessor: "contactNumber",
    disableFilters: true,
  },
  {
    Header: "Interview Appointment",
    accessor: "interview",
    disableFilters: true,
  },
  {
    Header: "Date Applied",
    accessor: "date",
    Filter: SelectColumnFilter,
    filter: "includes",
  },
  {
    Header: "Status",
    accessor: "status",
    Filter: SelectColumnFilter,
    filter: "includes",
  },
];

export const jobData = [
  {
    id: "1",
    title: "Junior Dev",
    location: "Remote",
    salary: "25000",
    company: "Not Real LTD",
    date: new Date().toDateString(),
    status: "Pending",
    benefits: "Health, Casual Dress, 25 Day Holiday",
    contactName: "John Smith",
    contactNumber: "01234567890",
    interview: "",
  },
  {
    id: "2",
    title: "Junior React Dev",
    location: "Bracknell",
    salary: "30000",
    company: "Some Company LTD",
    date: new Date().toDateString(),
    status: "Interview",
    benefits: "28 Day Holiday",
    contactName: "Alan Smith",
    contactNumber: "01234567890",
    interview: "",
  },
  {
    id: "3",
    title: "Front End Dev",
    location: "Bristol",
    salary: "22000",
    company: "Bristol LTD",
    date: new Date().toDateString(),
    status: "Rejected",
    benefits: "Health, Casual Dress, 25 Day Holiday,",
    contactName: "Jane Doe",
    contactNumber: "01234567890",
    interview: "",
  },
  {
    id: "4",
    title: "Junior Dev",
    location: "Remote",
    salary: "25000",
    company: "Not Real LTD",
    date: new Date().toDateString(),
    status: "Expired",
    benefits: "Health, Casual Dress, 25 Day Holiday",
    contactName: "John Smith",
    contactNumber: "01234567890",
    interview: "",
  },
  {
    id: "5",
    title: "Junior React Dev",
    location: "Bracknell",
    salary: "30000",
    company: "Some Company LTD",
    date: new Date().toDateString(),
    status: "Pending",
    benefits: "28 Day Holiday",
    contactName: "Alan Smith",
    contactNumber: "01234567890",
    interview: "",
  },
  {
    id: "6",
    title: "Front End Dev",
    location: "Bristol",
    salary: "22000",
    company: "Bristol LTD",
    date: new Date().toDateString(),
    status: "Pending",
    benefits: "Health, Casual Dress, 25 Day Holiday,",
    contactName: "Jane Doe",
    contactNumber: "01234567890",
    interview: "",
  },
  {
    id: "7",
    title: "Junior Dev",
    location: "Remote",
    salary: "25000",
    company: "Not Real LTD",
    date: new Date().toDateString(),
    status: "Pending",
    benefits: "Health, Casual Dress, 25 Day Holiday",
    contactName: "John Smith",
    contactNumber: "01234567890",
    interview: "",
  },
  {
    id: "8",
    title: "Junior React Dev",
    location: "Bracknell",
    salary: "30000",
    company: "Some Company LTD",
    date: new Date().toDateString(),
    status: "Pending",
    benefits: "28 Day Holiday",
    contactName: "Alan Smith",
    contactNumber: "01234567890",
    interview: "",
  },
  {
    id: "9",
    title: "Front End Dev",
    location: "Bristol",
    salary: "22000",
    company: "Bristol LTD",
    date: new Date().toDateString(),
    status: "Pending",
    benefits: "Health, Casual Dress, 25 Day Holiday,",
    contactName: "Jane Doe",
    contactNumber: "01234567890",
    interview: "",
  },
  {
    id: "10",
    title: "Junior Dev",
    location: "Remote",
    salary: "25000",
    company: "Not Real LTD",
    date: new Date().toDateString(),
    status: "Pending",
    benefits: "Health, Casual Dress, 25 Day Holiday",
    contactName: "John Smith",
    contactNumber: "01234567890",
    interview: "",
  },
  {
    id: "11",
    title: "Junior React Dev",
    location: "Bracknell",
    salary: "30000",
    company: "Some Company LTD",
    date: new Date().toDateString(),
    status: "Pending",
    benefits: "28 Day Holiday",
    contactName: "Alan Smith",
    contactNumber: "01234567890",
    interview: "",
  },
  {
    id: "12",
    title: "Front End Dev",
    location: "Bristol",
    salary: "22000",
    company: "Bristol LTD",
    date: new Date().toDateString(),
    status: "Pending",
    benefits: "Health, Casual Dress, 25 Day Holiday,",
    contactName: "Jane Doe",
    contactNumber: "01234567890",
    interview: "",
  },
];

export const statusOptions = ["Pending", "Interview", "Rejected", "Expired"];
export const centeredColumns = ["Salary", "Contact Number", "Date Applied", "Status"];
